<a href="https://colab.research.google.com/github/usamanisar20/Python-projects/blob/main/Model_Selection_and_Grid_Search_(White_Wine).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy import *

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
dataset = pd.read_csv('/content/White Wine Quality.csv')

In [ ]:
dataset

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.0              0.27         0.36  ...       0.45      8.8        6
1               6.3              0.30         0.34  ...       0.49      9.5        6
2               8.1              0.28         0.40  ...       0.44     10.1        6
3               7.2              0.23         0.32  ...       0.40      9.9        6
4               7.2              0.23         0.32  ...       0.40      9.9        6
...             ...               ...          ...  ...        ...      ...      ...
4893            6.2              0.21         0.29  ...       0.50     11.2        6
4894            6.6              0.32         0.36  ...       0.46      9.6        5
4895            6.5              0.24         0.19  ...       0.46      9.4        6
4896            5.5              0.29         0.30  ...       0.38     12.8        7
4897            6.0              0.21         0.38  ...       0.32     11.8        6

[4898 rows x 12 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [ ]:
dataset.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
dataset['quality'] = [1 if i > 6.5 else 0 for i in dataset['quality']]

In [ ]:
dataset

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.0              0.27         0.36  ...       0.45      8.8        0
1               6.3              0.30         0.34  ...       0.49      9.5        0
2               8.1              0.28         0.40  ...       0.44     10.1        0
3               7.2              0.23         0.32  ...       0.40      9.9        0
4               7.2              0.23         0.32  ...       0.40      9.9        0
...             ...               ...          ...  ...        ...      ...      ...
4893            6.2              0.21         0.29  ...       0.50     11.2        0
4894            6.6              0.32         0.36  ...       0.46      9.6        0
4895            6.5              0.24         0.19  ...       0.46      9.4        0
4896            5.5              0.29         0.30  ...       0.38     12.8        1
4897            6.0              0.21         0.38  ...       0.32     11.8        0

[4898 rows x 12 columns]

In [ ]:
dataset['quality'].value_counts()

0    3838
1    1060
Name: quality, dtype: int64

In [ ]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
x

array([[ 7.  ,  0.27,  0.36, ...,  3.  ,  0.45,  8.8 ],
       [ 6.3 ,  0.3 ,  0.34, ...,  3.3 ,  0.49,  9.5 ],
       [ 8.1 ,  0.28,  0.4 , ...,  3.26,  0.44, 10.1 ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  2.99,  0.46,  9.4 ],
       [ 5.5 ,  0.29,  0.3 , ...,  3.34,  0.38, 12.8 ],
       [ 6.  ,  0.21,  0.38, ...,  3.26,  0.32, 11.8 ]])

In [ ]:
y

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
models = []
models.append(['Logistic Regression 1', LogisticRegression(C = 0.1)])
models.append(['Logistic Regression 2', LogisticRegression(C = 0.5)])
models.append(['Logistic Regression 3', LogisticRegression(C = 1.0)])

for m in range(len(models)):
  model = models[m][1]
  model.fit(x_train, y_train)
  y_pred = model.predict(x_test)
  cm = confusion_matrix(y_test, y_pred)
  accuracies = cross_val_score(estimator = model, X = x_train, y = y_train, cv = 10)
  print(models[m][0])
  print(cm)
  print('Accuracy Score',accuracy_score(y_test, y_pred))
  print("Mean Accuracy: {:.2f} %".format(accuracies.mean()*100))
  print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))
  print('-----------------------------------')

Logistic Regression 1
[[730  34]
 [167  49]]
Accuracy Score 0.7948979591836735
Mean Accuracy: 80.22 %
Standard Deviation: 1.29 %
-----------------------------------
Logistic Regression 2
[[730  34]
 [166  50]]
Accuracy Score 0.7959183673469388
Mean Accuracy: 79.96 %
Standard Deviation: 1.48 %
-----------------------------------
Logistic Regression 3
[[730  34]
 [165  51]]
Accuracy Score 0.7969387755102041
Mean Accuracy: 79.86 %
Standard Deviation: 1.56 %
-----------------------------------


In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
parameters = [{'n_estimators': [50, 100, 200, 300, 400, 500, 1000], 'criterion': ['gini']},
              {'n_estimators': [50, 100, 200, 300, 400, 500, 1000], 'criterion': ['entropy']}]
# grid_search = GridSearchCV(estimator = model,
#                            param_grid = parameters,
#                            scoring = 'accuracy',
#                            cv = 10,
#                            n_jobs = -1)
# clf = LogisticRegression()
# grid_values = {'penalty': ['l1', 'l2'],'C':[0.001,.009,0.01,.09,1,5,10,25]}
# grid_search = GridSearchCV(clf, param_grid = grid_values,scoring = 'recall')
grid={
    "C": np.logspace(-3,5,7), 
    "solver": ["lbfgs", "liblinear",],
    "penalty":["l1","l2"], 
    "max_iter": np.arange(100, 1000, 100)
    }
logreg=LogisticRegression()
scoring = ['roc_auc_ovr', 'f1_weighted', 'accuracy']
logreg.get_params
grid_search = GridSearchCV(estimator=logreg,
                     param_grid=grid,
                     scoring=scoring,
                     cv=5,
                     refit='roc_auc_ovr',
                     n_jobs=-1,
                     return_train_score=True
                    )
grid_search.fit(x_train, y_train)

return_train_score=True
# grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
best_std = grid_search.cv_results_['std_test_score']

KeyError: ignored

In [ ]:
  model = models[m][1]
  model.fit(x_train, y_train)
  y_pred = model.predict(x_test)
  cm = confusion_matrix(y_test, y_pred)
  accuracies = cross_val_score(estimator = model, X = x_train, y = y_train, cv = 10)
  print(models[m][0])
  print(cm)


Logistic Regression 3
[[730  34]
 [165  51]]


In [ ]:

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(y.shape)

        def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

IndentationError: ignored